import json
import os
import urllib.request
from pathlib import Path

USER = "mahrukh89"
TOKEN = os.environ.get("GITHUB_TOKEN", "")

def get_json(url):
    req = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {TOKEN}",
            "X-GitHub-Api-Version": "2022-11-28",
        },
    )
    with urllib.request.urlopen(req, timeout=20) as response:
        return json.load(response)

profile = get_json(f"https://api.github.com/users/{USER}")
repos = get_json(f"https://api.github.com/users/{USER}/repos?per_page=100&sort=updated")

public_repos = profile.get("public_repos", 0)
followers = profile.get("followers", 0)
stars = sum(r.get("stargazers_count", 0) for r in repos)
forks = sum(r.get("forks_count", 0) for r in repos)

svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="190" viewBox="0 0 1200 190">
<rect width="1200" height="190" rx="14" fill="#0d1117" stroke="#1f6feb"/>
<text x="35" y="35" fill="#58a6ff" font-family="monospace" font-size="15" font-weight="700">PORTFOLIO PULSE • LIVE GITHUB DATA</text>

<g font-family="Arial,Helvetica,sans-serif" text-anchor="middle">
<rect x="30" y="60" width="255" height="90" rx="9" fill="#111c29" stroke="#19395c"/>
<text x="157" y="92" fill="#8b949e" font-size="13">PUBLIC REPOSITORIES</text>
<text x="157" y="128" fill="#58a6ff" font-size="32" font-weight="700">{public_repos}</text>

<rect x="315" y="60" width="255" height="90" rx="9" fill="#111c29" stroke="#19395c"/>
<text x="442" y="92" fill="#8b949e" font-size="13">TOTAL REPOSITORY STARS</text>
<text x="442" y="128" fill="#3fb950" font-size="32" font-weight="700">{stars}</text>

<rect x="600" y="60" width="255" height="90" rx="9" fill="#111c29" stroke="#19395c"/>
<text x="727" y="92" fill="#8b949e" font-size="13">FOLLOWERS</text>
<text x="727" y="128" fill="#d2a8ff" font-size="32" font-weight="700">{followers}</text>

<rect x="885" y="60" width="285" height="90" rx="9" fill="#111c29" stroke="#19395c"/>
<text x="1027" y="92" fill="#8b949e" font-size="13">TOTAL REPOSITORY FORKS</text>
<text x="1027" y="128" fill="#f2cc60" font-size="32" font-weight="700">{forks}</text>
</g>

<text x="600" y="177" text-anchor="middle" fill="#6e7681" font-family="monospace" font-size="11">Generated by Python • GitHub Actions • live account data</text>
</svg>"""

Path("assets/portfolio-pulse.svg").write_text(svg, encoding="utf-8")
